name = "MusicTheory"
uuid = "564e61e1-4667-41b2-a4a2-754a0240c775"
authors = ["David Sanders <dpsanders@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
